version: '2.21'
services:
  redis:
    image: redis:alpine3.18
    hostname: redis
    container_name: redis1
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - .:/TrackingDocker

  # worker:
  #   build: 
  #     context: .
  #   hostname: worker
  #   entrypoint: celery
  #   command: -A celery_config.app worker -l INFO
  #   volumes:
  #     - .:/TrackingDocker
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  # flower:
  #   build: 
  #     context: .
  #   hostname: flower
  #   entrypoint: celery
  #   command: -A celery_config.app flower
  #   volumes:
  #     - .:/TrackingDocker
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  #   ports:
  #     - "5555:5555"
    